//** STAFF REGISTRATIONS */
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//**CLOSING STAFF REGISTRATIONS */
export const CLOSE_REQUEST = 'CLOSE_REQUEST';
export const CLOSE_SUCCESS = 'CLOSE_SUCCESS';
export const CLOSE_FAILURE = 'CLOSE_FAILURE';